### ISSUE TITLE
Fatal error on start

### ISSUE THREAD

**Issue by ryanmagoon** [workshopper/how-to-markdown#19]
I just installed the workshopper today and I'm getting this error:

```
/usr/local/lib/node_modules/how-to-markdown/node_modules/workshopper-adventure/lib/commands/menu.js:46
    title: __('title'),
           ^

TypeError: __ is not a function
    at Object.exports.handler (/usr/local/lib/node_modules/how-to-markdown/node_modules/workshopper-adventure/lib/commands/menu.js:46:12)
    at Object.explicit.execute.$ (/usr/local/lib/node_modules/how-to-markdown/node_modules/commandico/commandico.js:143:15)
    at applyObject (/usr/local/lib/node_modules/how-to-markdown/node_modules/explicit/plugin/_util/argValidator.js:52:19)
    at Object.applyArray (/usr/local/lib/node_modules/how-to-markdown/node_modules/explicit/plugin/_util/argValidator.js:68:12)
    at Object.execute (/usr/local/lib/node_modules/how-to-markdown/node_modules/explicit/plugin/assert/index.js:20:24)
    at WA.execute (/usr/local/lib/node_modules/how-to-markdown/node_modules/workshopper-adventure/index.js:113:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/how-to-markdown/bin/how-to-markdown:3:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
```

any ideas?

**Comment by denysdovhan** [comment]
@martinheidegger is that a problem in `workshopper-adventure`?

**Comment by martinheidegger** [comment]
@denysdovhan yes: Please update the dependency to 5.0.3
